"""
Figure-space text
==================

``fig.text(x, y, s)`` places text at figure-fraction coordinates -- ``(0, 0)``
bottom-left, ``(1, 1)`` top-right -- independent of any axes' data
coordinates. Handy for a watermark or a caption that shouldn't move with the
plotted data.
"""
import numpy as np
import plotpress

x = np.linspace(0, 10, 200)

fig, ax = plotpress.subplots()
ax.plot(x, np.sin(x))
fig.text(0.99, 0.01, "generated by plotpress", ha="right", va="bottom",
         fontsize=8, color="#999999")
fig.text(0.5, 0.5, "DRAFT", ha="center", va="center", fontsize=40,
         color="#f0c0c0")
